# Generated by Django 4.2.4 on 2023-08-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniproyecto_9', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='puntaje_usuario',
            field=models.IntegerField(default=0),
        ),
    ]
